export const INCREASE_COUNTER = 'INCREASE_COUNTER_ASYNC'

export const DECREASE_COUNTER = 'DECREASE_COUNTER'

export const GET_ALL_STORE = 'GET_ALL_STORE'

export const GET_STORES_CATEGORY = 'GET_STORES_CATEGORY'

export const ADD_TO_CART = 'ADD_TO_CART'

export const CURRENT_LOCATION = 'CURRENT_LOCATION'

export const CURRENT_ADDRESS = 'CURRENT_ADDRESS'